name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: pub get
        run: flutter pub get

      # ↓ changed here ↓
      - name: flutter analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: flutter test
        run: flutter test --coverage

      - name: flutter build apk
        run: flutter build apk --release

      - name: Upload APK & coverage
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            coverage/lcov.info
