name: Flutter CI

# Trigger on pushes or PRs to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_test_build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Set up Flutter (latest stable channel)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependencies
      - name: pub get
        run: flutter pub get

      # 4. Static analysis
      - name: flutter analyze
        run: flutter analyze

      # 5. Run tests (with coverage)
      - name: flutter test
        run: flutter test --coverage

      # 6. Build Android APK
      - name: flutter build apk
        run: flutter build apk --release

      # 7. Upload APK & coverage report
      - name: Upload APK & coverage
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            coverage/lcov.info
